// Builds the "drop into your Hooks folder" installer zip for a guild on demand.
//
// The hook template ships with a placeholder URL line. We substitute the
// guild's real ingest URL + token at request time, so the user downloads a
// pre-configured zip and doesn't have to edit anything by hand. The zip
// also includes the VBS launcher and a short README.

import { readFileSync, existsSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { zipSync, strToU8 } from 'fflate';

const __dirname = dirname(fileURLToPath(import.meta.url));
const HOOK_DIR = join(__dirname, '..', '..', 'dcs-hook');

// Read source files once at boot — they don't change between requests.
const HOOK_TEMPLATE    = readFileSync(join(HOOK_DIR, 'dcsopt_hook.lua'), 'utf8');
const MISSION_TEMPLATE = readFileSync(join(HOOK_DIR, 'dcsopt_mission.lua'), 'utf8');

// The VBS launcher is generated by the hook itself on first run, but we
// also ship a copy in the zip so the user doesn't have to wait for the
// first heartbeat to see it appear (less confusing in the Hooks folder).
const LAUNCHER_VBS = `Set sh = CreateObject("WScript.Shell")\r\n` +
  `sh.Run """" & WScript.Arguments(0) & """ """ & WScript.Arguments(1) & """", 0, False\r\n`;

function readme(ingestUrl) {
  return [
    '== DCS:OPT OPS Bot — DCS Server Installer ==',
    '',
    'CONTENTS:',
    '  dcsopt_hook.lua      — main GameGUI hook (pre-configured with your URL)',
    '  dcsopt_mission.lua   — mission-script side (captures kills/traps/bombs)',
    '  dcsopt_launch.vbs    — silent-launcher helper (hides cmd windows)',
    '',
    'INSTALL:',
    '  1. Open your DCS Saved Games folder:',
    '       %USERPROFILE%\\Saved Games',
    '     (paste that into File Explorer\'s address bar)',
    '  2. Find the folder for your DCS variant (DCS, DCS.openbeta, DCS.server).',
    '  3. Go into that folder, then into "Scripts" then "Hooks" (create them if missing).',
    '  4. Drop ALL THREE files from this zip into that Hooks folder.',
    '  5. Restart your DCS server / DCS.',
    '',
    'VERIFY:',
    '  Check the dashboard\'s "DCS Server" page — within ~60 seconds of restart,',
    '  the status should turn green and show "Online" with the current mission.',
    '',
    'PRE-CONFIGURED URL (already baked into dcsopt_hook.lua — no editing needed):',
    '  ' + ingestUrl,
    '',
    'TROUBLESHOOTING:',
    '  - Check Saved Games\\<your variant>\\Logs\\dcs.log',
    '  - Search the log for "DCSOPT" — you should see:',
    '      DCSOPT: hook loaded',
    '      DCSOPT: launcher written: ...',
    '      DCSOPT: mission tracker installed (installed)',
    '  - If you only see "hook loaded", you missed dropping dcsopt_mission.lua',
    '    into the same folder.',
    '',
  ].join('\r\n');
}

export function buildInstallerZip(ingestUrl) {
  // Replace the placeholder URL line in the hook template with the real one.
  const hookConfigured = HOOK_TEMPLATE.replace(
    /url\s*=\s*"https:\/\/CHANGE-ME[^"]*"/,
    `url            = ${JSON.stringify(ingestUrl)}`,
  );
  const zipped = zipSync({
    'dcsopt_hook.lua':    strToU8(hookConfigured),
    'dcsopt_mission.lua': strToU8(MISSION_TEMPLATE),
    'dcsopt_launch.vbs':  strToU8(LAUNCHER_VBS),
    'README.txt':         strToU8(readme(ingestUrl)),
  }, { level: 6 });
  return Buffer.from(zipped);
}

export function hookTemplatesPresent() {
  return existsSync(join(HOOK_DIR, 'dcsopt_hook.lua'))
      && existsSync(join(HOOK_DIR, 'dcsopt_mission.lua'));
}
